import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import TanstackProvider from "@/providers/TanstackProvider";
import NavMobile from "@/components/shared/NavMobile";
import AuthProvider from "@/providers/AuthProvider";
import AppContexts from "@/providers/AppContexts";
import ThemeProvider from "@/providers/ThemeProvider";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppContexts>
              <AuthProvider>
                <Navbar />
                <NavMobile />
                {children}
                <Toaster />
                <Footer />
              </AuthProvider>
            </AppContexts>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
